import { notFound } from "next/navigation";
import { dbAdmin } from "@/lib/db";
import { siteSpecSchema } from "@/lib/site-spec";

export default async function PreviewPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const db = dbAdmin();
  const { data: site } = await db.from("generated_sites").select("*").eq("preview_slug", slug).single();
  if (!site) notFound();

  const parsed = siteSpecSchema.safeParse(site.site_spec_json);
  if (!parsed.success) notFound();
  const spec = parsed.data;

  return (
    <main className="min-h-screen bg-white text-zinc-900">
      <section className="bg-sky-50 px-6 py-16 text-center">
        <h1 className="text-4xl font-bold">{spec.hero.headline}</h1>
        <p className="mx-auto mt-3 max-w-xl text-zinc-700">{spec.hero.subheadline}</p>
        <button className="mt-6 rounded bg-sky-600 px-5 py-2 text-white">{spec.hero.cta}</button>
      </section>
      <section className="mx-auto max-w-5xl px-6 py-12">
        <h2 className="text-2xl font-semibold">{spec.services.title}</h2>
        <div className="mt-4 grid gap-4 md:grid-cols-3">
          {spec.services.items.map((item) => (
            <div key={item.name} className="rounded border p-4">
              <h3 className="font-semibold">{item.name}</h3>
              <p className="text-sm text-zinc-600">{item.description}</p>
            </div>
          ))}
        </div>
      </section>
      <section className="bg-zinc-50 px-6 py-12">
        <div className="mx-auto max-w-5xl space-y-3">
          <h2 className="text-2xl font-semibold">{spec.about.title}</h2>
          <p className="text-zinc-700">{spec.about.body}</p>
        </div>
      </section>
      <section className="mx-auto max-w-5xl px-6 py-12">
        <h2 className="text-2xl font-semibold">{spec.why_choose_us.title}</h2>
        <ul className="mt-4 list-disc space-y-2 pl-6 text-zinc-700">
          {spec.why_choose_us.points.map((point) => (
            <li key={point}>{point}</li>
          ))}
        </ul>
      </section>
      <section className="bg-zinc-900 px-6 py-12 text-white">
        <div className="mx-auto max-w-5xl space-y-2">
          <h2 className="text-2xl font-semibold">Contact</h2>
          <p>{spec.contact.phone}</p>
          <p>{spec.contact.address}</p>
          <p>{spec.contact.cta}</p>
        </div>
      </section>
      <section className="px-6 py-10 text-center">
        <p className="text-sm text-zinc-500">Generated by LocalLead AI preview builder.</p>
      </section>
    </main>
  );
}
